### ISSUE TITLE
Tornando o mod hardtoch mais intuitivo.

### ISSUE THREAD

**Issue by Lunovox** [BrunoMine/hardtorch#2]
Tem como por o mod Hardtorch para ter o uso mais intuitivo ao tornr o mod mais alto explicativo? 

Exemplo: 
 * Se o player tentar acender uma tocha/lamparina e não tiver nenhuma fonte de fogo ele recebe no chat um aviso tipo: ````[hardtorch] Você precisa de uma fonte de fogo, como isqueiro ou forno aceso, em seu inventário para acender este item.```` 
 * Se a lamparina tiver sem óleo vai receber o aviso: ````[hardtorch] Você precisa possuir algum óleo no seu inventario para poder acender esta lamparina.```` 

Eu estou sugerindo isso porque o servidor do animetron tem uma alta tacha de desistência dos players por não saberem como se desenvolver no server. Você pode ajudar?

**Comment by BrunoMine** [comment]
Boa ideia, mas talvez nao seja necessario exibir o nome do mod `hardtorch`. E deixar a frase simples como `Lamparina sem combustível` e `Sem acendedor (use esqueiro ou forno aceso)`.

**Comment by BrunoMine** [comment]
[Adicionado avisos de texto](https://github.com/BrunoMine/hardtorch/commit/10cb2d310e8d3f6b45426246395ba149f38dd81b)
