### ISSUE TITLE
torch goes on and off

### ISSUE THREAD

**Issue by Nordall** [BrunoMine/hardtorch#4]
Hello BrunoMine,
since I am using MTv5.1.0 and MTG 5.1.0 the torches go off anf on in a regular rhythm. This happens only, if I go down beyond a certain height. As long as I stay above it, the torch burns continiously as should be. I'll try to tell more precise data about the height border of working and not working torch.

**Comment by Nordall** [comment]
The border is -19. Because I use the "under_sky" mod and have the sky_start set to -19, the border is at 0. So under 0 the torch is getting on and off, above 0 it burns continously.

**Comment by BrunoMine** [comment]
I performed some tests. This problem happens even using only standard MG mods.

**Comment by BrunoMine** [comment]
This problem has been fixed. You can test it.
https://github.com/BrunoMine/hardtorch/commit/e542dd894f68a67bd6e80336e3f017e080c18602

**Comment by BrunoMine** [comment]
Thank you for report.
